### ISSUE TITLE
Math added -> time to get images to put on the window

### ISSUE THREAD

**Issue by dmbcalado** [gabriela-freitas/cub3d#13]
Added the math directory with the 2 files that calculate the rays of the ray casting.
I think is working just fine however some mlx implementations need to be added now, alongside importing the images to test if this is working fine.
Changed the name of map_size to map_height you were right, it does seam more straight forward, and fixed the calc going weird sometimes by looping it after creation of the map.
I'm back on C++ for now tell me if you need anything! 😃 🚀 
![Screenshot from 2023-02-14 00-21-08](https://user-images.githubusercontent.com/99777188/218606050-7def0f98-a472-4087-93b3-3555b2c690db.png)

**Comment by gabriela-freitas** [comment]
// if (keycode == key_D)
	// {
	// 	data->p.p_x += 0.2;
	// 	mathematics(data);
	// }

adiciona isso a key_code para testar o movement
