### ISSUE TITLE
Map checker 

### ISSUE THREAD

**Issue by dmbcalado** [gabriela-freitas/cub3d#2]
◦ The map must be closed/surrounded by walls, if not the program must return
an error.
◦ Except for the map content, each type of element can be separated by one or
more empty line(s).
◦ Except for the map content which always has to be the last, each type of
element can be set in any order in the file.
◦ Except for the map, each type of information from an element can be separated
by one or more space(s).
◦ The map must be parsed as it looks in the file. Spaces are a valid part of the
map and are up to you to handle. You must be able to parse any kind of map,
as long as it respects the rules of the map.

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 18-38-34](https://user-images.githubusercontent.com/85411324/218171580-78984748-17ab-4777-a0ac-d2690d8cdce3.png)
![Screenshot from 2023-02-10 18-38-56](https://user-images.githubusercontent.com/85411324/218171587-e6111b93-1e20-4658-8153-5f07df4b990f.png)

**Comment by gabriela-freitas** [comment]
11 1   1111 11
  10101  1   1001
  1000011011  11
  100110N0001
110111111011
10000000001
1111111111

**Comment by gabriela-freitas** [comment]
11 1   1111 11
  10101  1   1001
  1000011011  11
  100110N0001
110111111011
10000000001
1111111111

**Comment by gabriela-freitas** [comment]
`  11 1   1111 11
  10101  1   1001
  1000011011  11
  100110N0001
110111111011
10000000001
1111111111`

**Comment by gabriela-freitas** [comment]
```
  11 1   1111 11
  10101  1   1001
  1000011011  11
  100110N0001
110111111011
10000000001
1111111111
```

**Comment by gabriela-freitas** [comment]
```
  11 1   1111111
  10101  1   1001
  1000011011  11
  100110N0001
110111111011
10000000001
1111111111
```

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 18-45-29](https://user-images.githubusercontent.com/85411324/218172786-f9e7125c-01be-4da6-949b-dcc7a17e7ecb.png)

**Comment by gabriela-freitas** [comment]
```
  11 1   11111111111111111111
  10101 1001   10000000000001
  1000011011   10000000000001
  100110N0001  10000000000001
110111111011   11111111111111
10000000001      111000111
1111111111        111111
```

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 18-48-09](https://user-images.githubusercontent.com/85411324/218173215-b1efcbd2-6b03-4f0e-8c91-afa0ac28f163.png)

**Comment by gabriela-freitas** [comment]
```
  11 1   11111111111111111111
  10101 1001   10000000000001
  1000011011   10000000000001
  100110N0001  10000000000001
110111111011   11111111111111
10000000001      111000111
1111111111        111111
1111111111111111111111111111111
1111100000000000000000001111111
111110000000000000000011111
1111111100000000011111
111111111111111111
```

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 18-49-44](https://user-images.githubusercontent.com/85411324/218173644-dfe7e77c-9f5f-458d-800c-5ecfe0ed77ab.png)

**Comment by gabriela-freitas** [comment]
```
  11 1   11111111111111111111
  10101 1001   10000000000001
  1000011011   10000000000001
  100110N0001  10000000000001
110111111011   11111111111111
10000000001      111000111
1111111111        111111
1111111111111111111111111111111
1111100000000000000000001111111
    110000000000000000011111
    11111100000000011111
       1111111111
```

**Comment by dmbcalado** [comment]
![Screenshot from 2023-02-10 18-52-41](https://user-images.githubusercontent.com/99777188/218174153-ce6ba477-9a9a-44bb-a7c1-42ee680a6dbd.png)

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 19-07-57](https://user-images.githubusercontent.com/85411324/218176922-026c8bf9-1e7d-4940-8b20-af06879701a1.png)

**Comment by gabriela-freitas** [comment]
![Screenshot from 2023-02-10 19-10-09](https://user-images.githubusercontent.com/85411324/218177287-a6199e6d-25c7-4706-9966-838ed94c3fa7.png)

**Comment by dmbcalado** [comment]
Method changed to burning inside, way easier.
