### ISSUE TITLE
Segfault on Testmaps?

### ISSUE THREAD

**Issue by dmbcalado** [gabriela-freitas/cub3d#27]
Gabi nao sei porque da segfault nos mapas. Verifica isso pff nao consigo tirar screenshot que o pc da escola que estou a usar ta bugado mas e so testares com o test_map4.cub. Vou acabar agora o teste do mapa, assim fica tudo completo e so precisamos de lidar com este problema.

**Comment by gabriela-freitas** [comment]
Resolvido
